### PR TITLE
making compatible with older versions of dplyr

### PR DESCRIPTION
**Pull request by kwells4**

### CODE REVIEW

**Comment by jayhesselberth** [comment]
This actually addresses changes in the new dplyr. Could you use the approach here:

https://github.com/rnabioco/valr/commit/0006d38a6704899fcec2fdc626710d6ee2b07ca6

If left as is, we'd have to increase the dplyr version requirement.

**Comment by kwells4** [comment]
This now includes a `dplyr` version check before running `left_join`. [The `relationship` argument was gained in version 1.1.1](https://dplyr.tidyverse.org/news/index.html). I've tested on `dplyr` version 1.1.2 and 1.1.0 (where it previously gave the error about the `relationship` argument)

**Comment by jayhesselberth** [comment]
It's probably easier to just take a dependency on dplyr 1.1.1, most people should be keeping current at this point.

**Comment by jayhesselberth** [comment]
I.e., change this:

https://github.com/rnabioco/djvdj/blob/4f27269103a3ed32d5e9149560b9ff38ddc9a047/DESCRIPTION#L30

to

`dplyr (>= 1.1.1),`

**Pull request merged**
